-- Task 1: Claims health check every 5 minutes
CREATE OR REPLACE TASK TASK_CHECK_CLAIMS
    WAREHOUSE = SNOWGUARD_WH
    SCHEDULE  = '1 MINUTE'
AS CALL CHECK_CLAIMS_HEALTH();
 
-- Task 2: Policy health check every 5 minutes
CREATE OR REPLACE TASK TASK_CHECK_POLICY
    WAREHOUSE = SNOWGUARD_WH
    SCHEDULE  = '1 MINUTE'
AS CALL CHECK_POLICY_HEALTH();
 
-- Task 3: Premium health check every 5 minutes
CREATE OR REPLACE TASK TASK_CHECK_PREMIUM
    WAREHOUSE = SNOWGUARD_WH
    SCHEDULE  = '1 MINUTE'
AS CALL CHECK_PREMIUM_HEALTH();
 
-- IMPORTANT: Resume all tasks (they start suspended by default)
ALTER TASK TASK_CHECK_CLAIMS  RESUME;
ALTER TASK TASK_CHECK_POLICY  RESUME;
ALTER TASK TASK_CHECK_PREMIUM RESUME;
 
-- Task 4: Email alert after all health checks complete
CREATE OR REPLACE TASK TASK_ALERT_EMAIL
    WAREHOUSE = SNOWGUARD_WH
    SCHEDULE  = '1 MINUTE'
AS CALL CHECK_AND_ALERT_PIPELINES();

ALTER TASK TASK_ALERT_EMAIL RESUME;

-- Verify tasks are running
SHOW TASKS;

-- Stop all tasks
ALTER TASK SNOWGUARD_DB.INSURANCE.TASK_CHECK_CLAIMS SUSPEND;
ALTER TASK SNOWGUARD_DB.INSURANCE.TASK_CHECK_POLICY SUSPEND;
ALTER TASK SNOWGUARD_DB.INSURANCE.TASK_CHECK_PREMIUM SUSPEND;
ALTER TASK SNOWGUARD_DB.INSURANCE.TASK_ALERT_EMAIL SUSPEND;